<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.66" />
        <PackageReference Include="FluentMigrator" Version="7.2.0" />
        <PackageReference Include="FluentMigrator.Runner" Version="7.2.0" />
        <PackageReference Include="FluentMigrator.Runner.Postgres" Version="7.2.0" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
        <PackageReference Include="Npgsql" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DTO\Common\" />
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
